// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExampleOperator) DeepCopyInto(out *ExampleOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleOperator.
func (in *ExampleOperator) DeepCopy() *ExampleOperator {
	if in == nil {
		return nil
	}
	out := new(ExampleOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExampleOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExampleOperatorList) DeepCopyInto(out *ExampleOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExampleOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleOperatorList.
func (in *ExampleOperatorList) DeepCopy() *ExampleOperatorList {
	if in == nil {
		return nil
	}
	out := new(ExampleOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExampleOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExampleOperatorSpec) DeepCopyInto(out *ExampleOperatorSpec) {
	*out = *in
	out.OperatorSpec = in.OperatorSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleOperatorSpec.
func (in *ExampleOperatorSpec) DeepCopy() *ExampleOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(ExampleOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExampleOperatorStatus) DeepCopyInto(out *ExampleOperatorStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleOperatorStatus.
func (in *ExampleOperatorStatus) DeepCopy() *ExampleOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(ExampleOperatorStatus)
	in.DeepCopyInto(out)
	return out
}
